# Generated by Django 2.1.5 on 2019-01-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_iteminstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set item as returned'),)},
        ),
    ]
